blue_market/accounts/urls.py
from django.urls import path
from .views import (
    SignUpView, 
    manage_groups, 
    delete_group,
    edit_group,
    add_group,
)

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("manage-groups/", manage_groups, name="manage_groups"),
    path("add-group/", add_group, name="add_group"),
    path("edit-group/<pk>", edit_group, name="edit_group"),
    path("delete-group/<pk>", delete_group, name="delete_group"),
]

blue_market/blue_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from products.views import home

urlpatterns = [
    path("", home, name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('products/', include("products.urls"))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blue_market/products/models.py
from django.db import models
from django.conf import settings

# MODELO DE PRODUCTO
class Product(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="media", null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	return self.title

    @property
    def comments(self):
    	return self.comment_set.all()

    class Meta:
        ordering = ['-created_at']

# MODELO DE COMENTARIO
class Comment(models.Model):
 	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
 	post = models.ForeignKey(Product, on_delete=models.CASCADE)
 	text = models.TextField()
 	created_at = models.DateTimeField(auto_now_add=True)
 	
 	def __str__(self):
 		return self.text

 	class Meta:
 		ordering = ['-created_at']

# MODELO DE RESPUESTA DE COMENTARIO
class Reply(models.Model):
 	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="replies")
 	parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies")
 	text = models.CharField(max_length=100)
 	created_at = models.DateTimeField(auto_now_add=True)

 	def __str__(self):
 		return self.text

# MODELO DE REVIEW
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    rating = models.FloatField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


# MODELO DE TRANSACCION
class Transaction(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('debit', 'Debito'),
        ('currency', 'Divisas')
    ]
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="purchase")
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="seller")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHOD_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-created_at']

blue_market/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Blue Market{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/navbar-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/products-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/product-detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/product-confirm.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/rating.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blue_market/css/group-style.css' %}">
    <link rel="stylesheet" href="{% static 'blue_market/css/product-detele.css' %}">
</head>
<body>
  <!-- NAVBAR -->
    <header>
        <nav class="navbar bg-primary navbar-expand-lg float-right" data-bs-theme="dark">
          <div class="container-fluid">
            <a class="navbar-brand text-center fs-3 fw-medium title-company" href="{% url 'home' %}">Blue Market</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ms-auto pull-xs-right mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" href="{% url 'manage_groups' %}">Panel</a>
                </li>
                {% endif %}
                {% if perms.products.add_product %}
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" href="{% url 'list_products' %}">My products</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" href="{% url 'create_view' %}">Add Product</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" href="{% url 'sales' %}">My Sales</a>
                </li> 
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link active text-decoration-underline" href="{% url 'purchases' %}">My purchases</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link navbar-text active">@{{ user.username }}</a>
                </li>
                <li class="nav-item">
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <input class="nav-link navbar-text active btn-logout" type="submit" name="logout_user" id="logout_user" value="logout">
                  </form>
                </li>
                {% else %}
                <li>
                  <a class="right-text nav-link active text-decoration-underline" href="{% url "login" %}" class="btn btn-primary">Log In</a>
                </li>
                <li>
                  <a class="right-text nav-link active text-decoration-underline" href="{% url "signup" %}" class="btn btn-primary">Sign Up</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </body>
</html>

blue_market/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h2 class="text-center mt-5 mb-5 title">Products</h2>
<nav class="navbar bg-body-tertiary mb-3 w-50 mx-auto">
  <div class="container-fluid">
    <form class="d-flex mx-auto" role="search">
      <input class="form-control me-2 mx-auto" type="search" name="search" placeholder="Search" aria-label="Search" value="{{ query }}">
      <select name="order_by">
				<option value="">Select an option</option>
				<option value="price_asc" {% if order_by == 'price_asc' %}selected{% endif %}> Price-</option>
				<option value="price_desc" {% if order_by == 'price_desc' %}selected{% endif %}>Price+</option>
				<option value="rating" {% if order_by == 'rating' %}selected{% endif %}>Rating</option>
			</select>
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
<!-- TABLA DE PRODUCTOS --> 
<table class="table table-bordered container text-center">
  <thead>
    <tr>
		<th>Product</th>
		<th>Description</th>
		<th>Price</th>
		<th>Image</th>
		<th>User</th>
	</tr>
  </thead>
  <tbody class="table-group-divider">
    {% for p in products %}
	
	<tr>
		<td><p class="title-product"><a href="{% url "detail_product" p.id %}">{{ p.title|truncatechars:30 }}</a></p></td>
		<td><p class="description-product">{{ p.description|truncatechars:30 }}</p></td>
		<td><p class="price-product">${{ p.price }}</p></td>
		<td><p><img src="{{ p.image.url }}" alt="{{ p.image.title }}" class="mx-auto d-block"></p></td>
		<td>
			<p><span class="username-product">@{{ p.user }}</span></p>
		</td>
	</tr>

	{% endfor %}
  </tbody>
</table>
<div>
	{% include 'paginator.html' %}
</div>
{% endblock %}

blue_market/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}&search={{ query }}&order_by={{ order_by }}">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}&search={{ query }}&order_by={{ order_by }}">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}&search={{ query }}&order_by={{ order_by }}">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}&search={{ query }}&order_by={{ order_by }}">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}